version: v1
common:
  os: centos7                                   # 如无特殊情况，请使用centos7，不填会默认centos7.

build:
  run:
    workDir: ./                                 # workDir是代码仓库的相对目录
    cmd:
      - sh deploy/compile.sh                    # cd 进 workDir 后,相对于当前 pwd 下,调用哪个脚本进行打包
  target:
    distDir: ./                                 # distDir是代码仓库的相对目录
    files:                                      # files中的文件描述是相对distDir的
      - ./*
      - ./deploy
deploy:
    run:
      workDir: .
      cmd:
        - sh deploy/run.sh
